### ISSUE TITLE
Custom Race Not Saving Properly.

### ISSUE THREAD

**Issue by SparkleSparkle** [Verteiron/FamiliarFaces#113]
Hello, thank you for the fantastic mod, first of all. The first impression with it was a great and pleasant surprise. However, I have recently started to run into some issues that I have never encountered in the previous saves. I was forced to restart from scratch by me being stupid, removing some mods that caused save data to not load completely. So, I am starting anew and unfortunately, it seems that Familiar Faces is also having an issue. It had its fit by constantly giving Data/vMYC cannot be overwritten error or something. I kind of worked around that by completing Helgen related quest from Alternative Start. Then, issue arose when it comes to saving my chars. I am using Lykaios race characters to save and export them. The issue is, while MCM menu marks them as Lykaios, I see no sign of anything Lykaios from the characters. I only see default Nord races as figurines and when I summon them into my playthrough char's save, they indeed appear as Nords. I am wondering what is up with that. I'd like to think that I have all the needed files for Lykaios race. I got the main file, got the SOS's body and such. Thank you.

UPDATE: Just now, I now have invisible head glitch. I suspect that it is Lykaios related issue on that regard, and I do believe that its silentshoutfix version is the culprit, but I got nothing solid on not saving properly.

**Comment by Verteiron** [comment]
That's very strange, because I tested with the RaceMenu 3 beta from LoversLab and it worked fine for me. Perhaps @expired6978 has some insight here?

**Comment by expired6978** [comment]
Check skse_chargen.log, errors are reported on failure. If there's no error for
LoadJsonPreset or LoadBinaryPreset, then it's an issue on script side preventing the function from being called in the first place.

Load function only fails when the file doesn't exist, fails to be parsed (invalid json format), has no version information, no mod header, or doesn't meet the minimum version requirement. The last three are relatively redundant with the new json format so the only real point of failure would be the first two.

Make sure your version of FF has the minor changes to the script-sided file exists checks.

**Comment by Verteiron** [comment]
@SparkleSparkle Can you please try this release with RM3 and let me know if it resolves the problem for you? 

https://github.com/Verteiron/FamiliarFaces/releases/tag/v1.1.4

**Comment by SparkleSparkle** [comment]
I will get on to it today. Thank you.

**Comment by SparkleSparkle** [comment]
Seems like that fixed it. Thank you @Verteiron and @expired6978 for the extensive help. =)

**Comment by Verteiron** [comment]
Resolved with release of 1.1.4. Issue was related to #110.
