### ISSUE TITLE
Character renaming question

### ISSUE THREAD

**Issue by SilverIce** [Verteiron/FamiliarFaces#121]
Will renaming of a character and 'exporting' produce new hero/identity? I often change character style, appearance, name without switching to a new hero.

Or, it's better avoid this as it may create few character files with the same UUIDs?

**Comment by Verteiron** [comment]
In the current version yes. In the new version it uses uuids so you can
create a new "slot" with each export if you want.

**Comment by SilverIce** [comment]
Ok, thanks for reply
